---@type integer
local CONST_MAX_CELL_ENERGY = 14

---@type integer
local CONST_MIN_CELL_ENERGY = 9

---@type integer
local CONST_MAX_ENERGY_UPDATE = 9

---@type integer
local CONST_INITIAL_CELL_ENERGY = 30

local config = {
    CONST_INITIAL_CELL_ENERGY = CONST_INITIAL_CELL_ENERGY,
    CONST_MIN_CELL_ENERGY = CONST_MIN_CELL_ENERGY,
    CONST_MAX_CELL_ENERGY = CONST_MAX_CELL_ENERGY,
    CONST_MAX_ENERGY_UPDATE = CONST_MAX_ENERGY_UPDATE,
}

return config
