---@type integer
local CONST_MINIMAL_SUCCESS_ITERATIONS = 1000

---@type integer
local CONST_LOG_PRINTOUT_THRESHOLD = CONST_MINIMAL_SUCCESS_ITERATIONS / 100

---@type integer
local CONST_FRAME_PRINT_RATE = 1

---@type string[]
local CONST_VISUALIZATION_OPTIONS = {
    "always",
    "from_set_moment",
    "never",
}

---@type integer
local CONST_FPS = 0

---@type number
local CONST_FRAME_PERIOD = (CONST_FPS == 0) and 0 or 1/CONST_FPS

local config = {
    CONST_MINIMAL_SUCCESS_ITERATIONS = CONST_MINIMAL_SUCCESS_ITERATIONS,
    CONST_LOG_PRINTOUT_THRESHOLD = CONST_LOG_PRINTOUT_THRESHOLD,
    CONST_FRAME_PRINT_RATE = CONST_FRAME_PRINT_RATE,
    CONST_VISUALIZATION_MODE = CONST_VISUALIZATION_OPTIONS[2],
    CONST_FRAME_PERIOD = CONST_FRAME_PERIOD,
}

return config
